apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  # 🚀 Tells EKS Auto Mode to automatically create the PV disk for you
  storageClassName: ebs-auto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
