name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: namegen
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name devops-project --region us-west-2

      - name: Deploy Application Components to EKS
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: namegen
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s|namegen:latest|$REGISTRY/$REPOSITORY:$IMAGE_TAG|g" k8s/app-deployment.yaml
          
          kubectl apply -f k8s/app-service.yaml
          kubectl apply -f k8s/app-deployment.yaml

      - name: Print Public App URL Endpoint
        run: |
          sleep 15
          kubectl get svc namegen-app-service
